"""FPL squad optimizer: given per-player expected points and constraints, solve
for the optimal 15-man squad and starting XI under FPL's real rules.

FPL squad rules encoded here:
- 15 players total: exactly 2 GK, 5 DEF, 5 MID, 3 FWD.
- Total spend <= budget (default GBP100.0m, FPL's standard starting budget).
- At most 3 players from any single real-life club.
- Starting XI: exactly 1 GK, and at least 3 DEF / 2 MID / 1 FWD among the outfield
  10, matching FPL's minimum-per-position rule for a valid formation.

This is a pure optimization layer -- it takes a DataFrame of (player_id, position,
team, cost, predicted_points) and returns a squad. It doesn't care whether
predicted_points came from the trained xP model, FPL's own xP, or a manual
watchlist -- keeping the solver decoupled from the model makes it usable (and
testable) even before the model's live-gameweek predictions exist.
"""

import glob
import json
import os

import pandas as pd
import pulp

_POSITION_MAP = {1: "GK", 2: "DEF", 3: "MID", 4: "FWD"}


_DASHBOARD_BOOTSTRAP_FALLBACK = os.path.join("data", "dashboard_bootstrap.json")


def load_latest_prices(raw_data_dir: str = None) -> pd.DataFrame:
    """Load the most recent bootstrap snapshot's player prices (`now_cost`).

    Prices move week to week based on transfer momentum (FPL's own algorithm
    reacts to transfers_in_event/transfers_out_event), so ANY optimizer call --
    squad building or transfers -- should be fed prices from the latest
    collector run, never a cached/stale snapshot. This always picks the most
    recent bootstrap_*.json by filename (timestamps sort correctly), across
    every season folder the collector has written, so a call right after a
    weekly collector run automatically picks up that run's prices with no
    extra wiring.

    data/raw/ is entirely gitignored (personal manager data lives alongside
    the league-wide snapshots there, and it's regenerated by the collector
    anyway), so a fresh deploy environment (Streamlit Cloud, a new clone) has
    no bootstrap snapshot to read. Falls back to data/dashboard_bootstrap.json
    -- a single, deliberately-committed, non-timestamped copy kept for exactly
    this purpose -- when data/raw/ has nothing. That fallback goes stale
    between manual refreshes (see this repo's README, Future Improvements for
    automating it), so prefer a real collector run locally when one's available.

    Returns (player_id, name, position, team, cost) -- cost is current price
    only, not each squad member's individual sell price after the 50% profit
    fee (see optimize_transfers' sell_price_col parameter for that)."""
    raw_data_dir = raw_data_dir or os.path.join("data", "raw")
    pattern = os.path.join(raw_data_dir, "*", "bootstrap", "bootstrap_*.json")
    paths = sorted(glob.glob(pattern))

    if paths:
        source_path = paths[-1]
    elif os.path.exists(_DASHBOARD_BOOTSTRAP_FALLBACK):
        source_path = _DASHBOARD_BOOTSTRAP_FALLBACK
    else:
        raise FileNotFoundError(
            f"No bootstrap snapshot found matching {pattern}, and no fallback at "
            f"{_DASHBOARD_BOOTSTRAP_FALLBACK} -- run the collector "
            f"(src/collector/snapshot.py) at least once first."
        )

    with open(source_path, encoding="utf-8") as f:
        data = json.load(f)

    teams_by_id = {t["id"]: t["name"] for t in data["teams"]}
    rows = [
        {
            "player_id": p["id"],
            "name": f"{p['first_name']} {p['second_name']}",
            "position": _POSITION_MAP[p["element_type"]],
            "team": teams_by_id[p["team"]],
            "cost": p["now_cost"] / 10.0,  # FPL's API stores price in tenths
        }
        for p in data["elements"]
    ]
    return pd.DataFrame(rows)

SQUAD_SIZE = 15
POSITION_REQUIREMENTS = {"GK": 2, "DEF": 5, "MID": 5, "FWD": 3}
MAX_PER_TEAM = 3
DEFAULT_BUDGET = 100.0

STARTING_XI_SIZE = 11
STARTING_XI_MIN = {"GK": 1, "DEF": 3, "MID": 2, "FWD": 1}

# Verified live against the FPL API's bootstrap-static game_settings (2026-27
# season), not assumed:
POINTS_PER_HIT = 4  # cost per transfer beyond the free ones

# NOT part of FPL's rules -- these are this project's own bar for when a
# transfer is worth RECOMMENDING, separate from what's merely legal. Without
# them, optimize_transfers happily proposes every transfer with even a
# fractional positive gain once free transfers make it "cost nothing" in the
# objective (e.g. a 5th free transfer for +0.4 predicted points) -- technically
# optimal, but not something a real manager should act on: churn has its own
# cost (giving up banked transfers, chasing noise in the prediction) that the
# raw objective doesn't see. Free transfers get a real but low bar (must beat
# noise); paid transfers get a materially higher one, since a hit needs the
# gain to clearly outweigh a real, certain -4pt cost, not just eke past it --
# the model's own validation MAE (~1 point per player-gameweek, see README) is
# larger than a marginal net gain would be, so "barely positive after the hit"
# is well within the model's own error bar, not a genuine edge.
MIN_GAIN_PER_FREE_TRANSFER = 1.0
MIN_NET_GAIN_PER_HIT = 2.0
MAX_FREE_TRANSFERS_BANKED = 4  # max_extra_free_transfers -> 1 (this week) + 4 banked = 5 max
SELL_ON_FEE = 0.5  # transfers_sell_on_fee: only 50% of a price RISE is kept on sale
CHIP_HALVES = {
    "first_half": (1, 19),   # start_event 1/2, stop_event 19
    "second_half": (20, 38),  # start_event 20, stop_event 38
}
CHIPS = ["wildcard", "freehit", "bboost", "3xc"]  # one of each usable per half


def optimize_squad(
    players: pd.DataFrame,
    budget: float = DEFAULT_BUDGET,
    id_col: str = "player_id",
    position_col: str = "position",
    team_col: str = "team",
    cost_col: str = "cost",
    points_col: str = "predicted_points",
) -> pd.DataFrame:
    """Solve for the 15-man squad that maximizes total predicted points, subject
    to FPL's squad-composition, budget, and per-team constraints.

    Returns the input DataFrame filtered to the selected 15 players, with an
    added `in_starting_xi` column marking the optimal starting XI within that
    squad (a separate, nested optimization -- see select_starting_xi)."""
    required_cols = {id_col, position_col, team_col, cost_col, points_col}
    missing = required_cols - set(players.columns)
    if missing:
        raise ValueError(f"players DataFrame is missing required columns: {missing}")

    unknown_positions = set(players[position_col].unique()) - set(POSITION_REQUIREMENTS)
    if unknown_positions:
        raise ValueError(f"Unexpected position values (expected GK/DEF/MID/FWD): {unknown_positions}")

    prob = pulp.LpProblem("fpl_squad_selection", pulp.LpMaximize)

    player_ids = players[id_col].tolist()
    pick = pulp.LpVariable.dicts("pick", player_ids, cat="Binary")

    points = players.set_index(id_col)[points_col].to_dict()
    cost = players.set_index(id_col)[cost_col].to_dict()
    position = players.set_index(id_col)[position_col].to_dict()
    team = players.set_index(id_col)[team_col].to_dict()

    # Objective: maximize total predicted points across the 15-man squad.
    prob += pulp.lpSum(pick[pid] * points[pid] for pid in player_ids)

    # Exactly 15 players.
    prob += pulp.lpSum(pick[pid] for pid in player_ids) == SQUAD_SIZE

    # Budget.
    prob += pulp.lpSum(pick[pid] * cost[pid] for pid in player_ids) <= budget

    # Exact position quotas (2 GK, 5 DEF, 5 MID, 3 FWD).
    for pos, quota in POSITION_REQUIREMENTS.items():
        pos_ids = [pid for pid in player_ids if position[pid] == pos]
        prob += pulp.lpSum(pick[pid] for pid in pos_ids) == quota

    # At most 3 players per real club.
    for club in set(team.values()):
        club_ids = [pid for pid in player_ids if team[pid] == club]
        prob += pulp.lpSum(pick[pid] for pid in club_ids) <= MAX_PER_TEAM

    status = prob.solve(pulp.PULP_CBC_CMD(msg=0))
    if pulp.LpStatus[status] != "Optimal":
        raise RuntimeError(
            f"Solver did not find an optimal solution (status: {pulp.LpStatus[status]}). "
            f"Check that enough players exist per position/budget/team constraints."
        )

    selected_ids = [pid for pid in player_ids if pick[pid].value() == 1]
    squad = players[players[id_col].isin(selected_ids)].copy()

    starting_ids = select_starting_xi(squad, id_col, position_col, points_col)
    squad["in_starting_xi"] = squad[id_col].isin(starting_ids)

    return squad.sort_values([position_col, points_col], ascending=[True, False]).reset_index(drop=True)


def select_starting_xi(
    squad: pd.DataFrame, id_col: str, position_col: str, points_col: str
) -> list:
    """Given a fixed 15-man squad, pick the 11 starters that maximize predicted
    points subject to FPL's formation rule (1 GK, >=3 DEF, >=2 MID, >=1 FWD).
    Public (not module-private) since callers outside this module legitimately
    need it too -- e.g. a manually-entered squad still wants an optimal
    starting XI computed for it, not the manager picking one by hand."""
    prob = pulp.LpProblem("fpl_starting_xi", pulp.LpMaximize)

    player_ids = squad[id_col].tolist()
    start = pulp.LpVariable.dicts("start", player_ids, cat="Binary")

    points = squad.set_index(id_col)[points_col].to_dict()
    position = squad.set_index(id_col)[position_col].to_dict()

    prob += pulp.lpSum(start[pid] * points[pid] for pid in player_ids)
    prob += pulp.lpSum(start[pid] for pid in player_ids) == STARTING_XI_SIZE

    gk_ids = [pid for pid in player_ids if position[pid] == "GK"]
    prob += pulp.lpSum(start[pid] for pid in gk_ids) == STARTING_XI_MIN["GK"]

    for pos in ["DEF", "MID", "FWD"]:
        pos_ids = [pid for pid in player_ids if position[pid] == pos]
        prob += pulp.lpSum(start[pid] for pid in pos_ids) >= STARTING_XI_MIN[pos]

    status = prob.solve(pulp.PULP_CBC_CMD(msg=0))
    if pulp.LpStatus[status] != "Optimal":
        raise RuntimeError(f"Starting XI solver failed (status: {pulp.LpStatus[status]})")

    return [pid for pid in player_ids if start[pid].value() == 1]


def _solve_transfers_for_k(
    k: int,
    current_set: set,
    player_ids: list,
    points: dict,
    cost: dict,
    sell_price: dict,
    position: dict,
    team: dict,
    is_current: dict,
    bank: float,
) -> dict:
    """Solve for the best squad reachable by making EXACTLY k transfers (0 <= k
    <= len(current_set)). Factored out of optimize_transfers so the caller can
    solve across every k and compare -- fixing k directly (rather than letting
    the solver choose it freely against a hit-adjusted objective) is what makes
    it possible to apply this project's own minimum-gain bar per transfer
    afterwards; the raw objective alone has no notion of "not worth the churn,"
    only "technically nonnegative.\""""
    prob = pulp.LpProblem(f"fpl_transfer_k{k}", pulp.LpMaximize)
    pick = pulp.LpVariable.dicts(f"pick_k{k}", player_ids, cat="Binary")

    prob += pulp.lpSum(
        pick[pid] * (sell_price[pid] if is_current[pid] else cost[pid])
        for pid in player_ids
    ) <= bank + pulp.lpSum(sell_price[pid] for pid in player_ids if is_current[pid])

    prob += pulp.lpSum(pick[pid] for pid in player_ids) == SQUAD_SIZE
    for pos, quota in POSITION_REQUIREMENTS.items():
        pos_ids = [pid for pid in player_ids if position[pid] == pos]
        prob += pulp.lpSum(pick[pid] for pid in pos_ids) == quota
    for club in set(team.values()):
        club_ids = [pid for pid in player_ids if team[pid] == club]
        prob += pulp.lpSum(pick[pid] for pid in club_ids) <= MAX_PER_TEAM

    prob += pulp.lpSum(1 - pick[pid] for pid in player_ids if is_current[pid]) == k
    prob += pulp.lpSum(pick[pid] * points[pid] for pid in player_ids)

    status = prob.solve(pulp.PULP_CBC_CMD(msg=0))
    if pulp.LpStatus[status] != "Optimal":
        return None

    new_squad_ids = [pid for pid in player_ids if pick[pid].value() == 1]
    return {
        "new_squad_ids": new_squad_ids,
        "total_points": sum(points[pid] for pid in new_squad_ids),
    }


def optimize_transfers(
    current_squad_ids: list,
    players: pd.DataFrame,
    free_transfers: int,
    bank: float = 0.0,
    max_paid_transfers: int = 3,
    id_col: str = "player_id",
    position_col: str = "position",
    team_col: str = "team",
    cost_col: str = "cost",
    points_col: str = "predicted_points",
    sell_price_col: str = None,
    min_gain_per_free_transfer: float = MIN_GAIN_PER_FREE_TRANSFER,
    min_net_gain_per_hit: float = MIN_NET_GAIN_PER_HIT,
) -> dict:
    """Given an existing 15-man squad and a number of banked free transfers,
    solve for the transfer(s) -- if any -- worth actually making.

    Solves separately for every possible transfer count k (0, 1, 2, ... up to
    free_transfers + max_paid_transfers), then picks the largest k whose gain
    clears this project's own recommendation bar -- NOT just "the k with the
    highest raw objective value," which is what a single combined solve would
    give and is why the old version of this function recommended a 5th free
    transfer for a +0.4 point gain (technically positive, not something a real
    manager should act on). The bar:
      - Within free_transfers: the AVERAGE gain per transfer used must be >=
        min_gain_per_free_transfer. A free transfer still has a real cost --
        it's a banked resource, and churn chases noise in a model with ~1 point
        of validation MAE per player-gameweek (see README) -- so "positive" and
        "worth using" aren't the same bar.
      - Beyond free_transfers (paid, taking a -4pt hit each): the NET gain from
        those specific additional transfers (after their hit cost) must be >=
        min_net_gain_per_hit, a real safety margin over just "breaks even,"
        since a marginal net gain is well within the model's own prediction
        error and isn't a genuine edge worth a certain, real point deduction.
    k=0 (hold) always clears the bar trivially, so this never fails to return a
    "no transfer is worth it" result when nothing beats it -- holding is never
    penalized just because SOME transfer exists with fractional positive value.

    IMPORTANT: `players` must carry CURRENT prices, not a stale snapshot -- FPL
    moves individual players' prices week to week based on transfer momentum, so
    a squad valuation (and therefore how much budget is actually available for
    incoming transfers) computed from last week's prices can be wrong. Use
    load_latest_prices() to always pull the most recent collector snapshot
    rather than caching a DataFrame across gameweeks.

    `free_transfers` should already reflect FPL's real banking rule (1 per week,
    capped at MAX_FREE_TRANSFERS_BANKED extra -- i.e. 5 max in a single week, not
    enforced here since that's a season-long bookkeeping concern for the caller,
    not something this one-gameweek solver needs to police).

    `max_paid_transfers` bounds the search space -- without a cap the solver could
    in principle propose overhauling the whole squad for a marginal points gain
    at a steep hit cost, which is rarely the right real-world call; 3 is a
    reasonable ceiling for a "how many transfers should I actually make" search.

    `sell_price_col`: FPL only refunds SELL_ON_FEE (50%) of any price RISE since
    purchase, not the full current price -- pass this column if you have each
    squad player's actual selling_price (from the FPL API's picks endpoint) for
    an accurate budget. Falls back to `cost_col` (current price) if not given,
    which OVERSTATES available budget for any player who's risen in price since
    being bought -- a known simplification, not a silent bug (see docstring note
    below and the CAVEAT in this function's return value).

    Returns a dict: {
        "transfers_out": [player_id, ...],
        "transfers_in": [player_id, ...],
        "num_paid_transfers": int,
        "hit_cost": int,               # points lost to hits
        "new_squad": DataFrame,        # same shape as optimize_squad's return
        "net_points_gain": float,      # predicted-points swing minus hit cost
    }"""
    if sell_price_col is None:
        sell_price_col = cost_col

    current_set = set(current_squad_ids)
    if not current_set.issubset(set(players[id_col])):
        missing = current_set - set(players[id_col])
        raise ValueError(f"current_squad_ids contains ids not present in players: {missing}")
    if len(current_set) != SQUAD_SIZE:
        raise ValueError(f"current_squad_ids must have exactly {SQUAD_SIZE} players, got {len(current_set)}")

    player_ids = players[id_col].tolist()
    is_current = {pid: (pid in current_set) for pid in player_ids}

    points = players.set_index(id_col)[points_col].to_dict()
    cost = players.set_index(id_col)[cost_col].to_dict()
    sell_price = players.set_index(id_col)[sell_price_col].to_dict()
    position = players.set_index(id_col)[position_col].to_dict()
    team = players.set_index(id_col)[team_col].to_dict()

    old_points = sum(points[pid] for pid in current_set)
    max_k = min(free_transfers + max_paid_transfers, SQUAD_SIZE)

    # Walk k = 1, 2, 3, ... UP from 0, solving for the best squad reachable at
    # each exact transfer count, and stop the FIRST time the MARGINAL gain of
    # going from k-1 to k doesn't clear that specific transfer's bar -- not the
    # average across all transfers so far. This is what stops a strong 1st/2nd
    # transfer from "subsidizing" a weak 5th one: each additional transfer has
    # to earn its own place, on top of whatever came before it, using whichever
    # bar applies to it (free-transfer bar while k <= free_transfers, the
    # stricter hit safety-margin bar once k goes beyond that).
    best_k = 0
    best_result = {"new_squad_ids": list(current_set), "total_points": old_points}
    prev_points = old_points
    for k in range(1, max_k + 1):
        candidate = _solve_transfers_for_k(
            k, current_set, player_ids, points, cost, sell_price, position, team, is_current, bank
        )
        if candidate is None:
            break  # infeasible at this k (e.g. budget/position constraints) -- can't go further

        marginal_gain = candidate["total_points"] - prev_points
        is_paid_step = k > free_transfers

        if is_paid_step:
            if marginal_gain - POINTS_PER_HIT < min_net_gain_per_hit:
                break  # this specific hit doesn't clear the safety margin on its own -- stop here
        else:
            if marginal_gain < min_gain_per_free_transfer:
                break  # this specific free transfer doesn't clear the bar on its own -- stop here

        best_k = k
        best_result = candidate
        prev_points = candidate["total_points"]

    new_squad_ids = best_result["new_squad_ids"]
    transfers_out = sorted(current_set - set(new_squad_ids))
    transfers_in = sorted(set(new_squad_ids) - current_set)
    num_paid_actual = max(0, len(transfers_out) - free_transfers)

    new_squad = players[players[id_col].isin(new_squad_ids)].copy()
    starting_ids = select_starting_xi(new_squad, id_col, position_col, points_col)
    new_squad["in_starting_xi"] = new_squad[id_col].isin(starting_ids)

    new_points = best_result["total_points"]
    hit_cost = POINTS_PER_HIT * num_paid_actual

    return {
        "transfers_out": transfers_out,
        "transfers_in": transfers_in,
        "num_paid_transfers": num_paid_actual,
        "hit_cost": hit_cost,
        "new_squad": new_squad.sort_values(
            [position_col, points_col], ascending=[True, False]
        ).reset_index(drop=True),
        "net_points_gain": (new_points - old_points) - hit_cost,
    }
